### ISSUE TITLE
Is plugin compatible with the recent release of TeamCity 10?

### ISSUE THREAD

**Issue by Kentzo** [guardian/teamcity-s3-plugin#16]
Have anyone already tried it?

**Comment by philwills** [comment]
I haven't tried it yet.

**Comment by eugene1g** [comment]
Works for us as it did with TC9

**Comment by nd** [comment]
Plugin is not compatible with TeamCity 10 due to [Open API changes](https://confluence.jetbrains.com/display/TCD10/Open+API+Changes). But it is easy to fix: you need to call `runningBuild.getBuildLog().message()` instead of `runningBuild.addBuildMessage()` at [ArtifactUploader.scala:15](https://github.com/guardian/teamcity-s3-plugin/blob/master/s3-plugin-server/src/main/scala/com/gu/teamcity/ArtifactUploader.scala#L15).

**Comment by JamesWoolfenden** [comment]
This is failing on Teamcity 10, ive tried compiling with boinst PR but that fails to compile. Using maven
 and java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

# build error

[ERROR] C:\code\boinst\s3-plugin-server\src\main\scala\com\gu\teamcity\ArtifactUploader.scala:15: error: overloaded method value message with alternatives:
[ERROR](x$1: String,x$2: jetbrains.buildServer.messages.Status,x$3: java.util.Date,x$4: String,x$5: String,x$6: java.util.Collection[String])jetbrains.buildServer.serverSide.buildLog.LogMessage <and>
[ERROR](x$1: String,x$2: jetbrains.buildServer.messages.Status,x$3: java.util.Date,x$4: String,x$5: String)jetbrains.buildServer.serverSide.buildLog.LogMessage
[ERROR]  cannot be applied to (jetbrains.buildServer.messages.BuildMessage1)
[ERROR]       runningBuild.getBuildLog().message(normalMessage(msg))
[ERROR]                                  ^
[ERROR] C:\code\boinst\s3-plugin-server\src\main\scala\com\gu\teamcity\ArtifactUploader.scala:27: error: overloaded method value message with alternatives:
[ERROR](x$1: String,x$2: jetbrains.buildServer.messages.Status,x$3: java.util.Date,x$4: String,x$5: String,x$6: java.util.Collection[String])jetbrains.buildServer.serverSide.buildLog.LogMessage <and>
[ERROR](x$1: String,x$2: jetbrains.buildServer.messages.Status,x$3: java.util.Date,x$4: String,x$5: String)jetbrains.buildServer.serverSide.buildLog.LogMessage
[ERROR]  cannot be applied to (jetbrains.buildServer.messages.BuildMessage1)
[ERROR]               runningBuild.getBuildLog().message(new BuildMessage1(DefaultMessagesInfo.SOURCE_ID, DefaultMessagesInfo.MSG_BUILD_FAILURE, Status.ERROR, new Date,
[INFO]                                          ^
[WARNING] warning: Class org.joda.convert.FromString not found - continuing with a stub.
[WARNING] warning: Class org.joda.convert.ToString not found - continuing with a stub.
[WARNING] warning: Class org.joda.convert.ToString not found - continuing with a stub.
[WARNING] warning: Class org.joda.convert.FromString not found - continuing with a stub.
[WARNING] warning: Class org.joda.convert.ToString not found - continuing with a stub.
[ERROR] C:\code\boinst\s3-plugin-server\src\main\scala\com\gu\teamcity\ManifestUploader.scala:39: error: overloaded method value message with alternatives:
[ERROR](x$1: String,x$2: jetbrains.buildServer.messages.Status,x$3: java.util.Date,x$4: String,x$5: String,x$6: java.util.Collection[String])jetbrains.buildServer.serverSide.buildLog.LogMessage <and>
[ERROR](x$1: String,x$2: jetbrains.buildServer.messages.Status,x$3: java.util.Date,x$4: String,x$5: String)jetbrains.buildServer.serverSide.buildLog.LogMessage
[ERROR]  cannot be applied to (jetbrains.buildServer.messages.BuildMessage1)
[ERROR]           case Failure(e) => runningBuild.getBuildLog().message(new BuildMessage1(DefaultMessagesInfo.SOURCE_ID, DefaultMessagesInfo.MSG_BUILD_FAILURE, Status.ERROR, new Date,
[INFO]                                                         ^
[ERROR] C:\code\boinst\s3-plugin-server\src\main\scala\com\gu\teamcity\ManifestUploader.scala:41: error: overloaded method value message with alternatives:
[ERROR](x$1: String,x$2: jetbrains.buildServer.messages.Status,x$3: java.util.Date,x$4: String,x$5: String,x$6: java.util.Collection[String])jetbrains.buildServer.serverSide.buildLog.LogMessage <and>
[ERROR](x$1: String,x$2: jetbrains.buildServer.messages.Status,x$3: java.util.Date,x$4: String,x$5: String)jetbrains.buildServer.serverSide.buildLog.LogMessage
[ERROR]  cannot be applied to (jetbrains.buildServer.messages.BuildMessage1)
[ERROR]           case Success(_) => runningBuild.getBuildLog().message(normalMessage("Manifest S3 upload complete"))

**Comment by x7n** [comment]
Looks like `runningBuild.getBuildLog().message()` is not excepting a parameter of `jetbrains.buildServer.messages.BuildMessage1` type. Just pass through all parameters according to the
[doc](http://javadoc.jetbrains.net/teamcity/openapi/8.1/jetbrains/buildServer/serverSide/buildLog/MessagesState.html#message%28java.lang.String, jetbrains.buildServer.messages.Status, java.util.Date, java.lang.String, java.lang.String%29) here and it works now!

**Comment by JamesWoolfenden** [comment]
@x7n could you submit the fix?

**Comment by x7n** [comment]
@JamesWoolfenden The pull request has been created. [Updated code for TeamCity 10 #19](https://github.com/guardian/teamcity-s3-plugin/pull/19)
