### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by Bikeman868** [guardian/teamcity-s3-plugin#23]
The install instructions say "To install the plugin, put zip archive to plugins dir under TeamCity data directory" but there are no zip files in the repo. Do I have to make the zip file myself first, and if so what files should I put in it?

**Comment by Kentzo** [comment]
You have to build it first. See the Build section in the README.

**Comment by Bikeman868** [comment]
What kind of dev environment do I need to build it?

**Comment by Kentzo** [comment]
If I recall correctly, you need Java and Maven.

Best Regards
Ilya Kulakov

**Comment by philwills** [comment]
You could build form source as @Kentzo suggests, but there is a pre-built zip you can find at https://github.com/guardian/teamcity-s3-plugin/releases

**Comment by Bikeman868** [comment]
Thanks
